<a href="https://colab.research.google.com/github/bramau9010/Arvores/blob/main/Leda_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

excel_file = "/content/drive/MyDrive/BASE DE DATOS. Rubi Armijos.xlsx"

# Get sheet names
excel_sheets = pd.ExcelFile(excel_file).sheet_names

# Load data from the first sheet into a dataframe
df1 = pd.read_excel(excel_file, sheet_name=excel_sheets[0])
print(f"Data from sheet '{excel_sheets[0]}':")
display(df1.head())

# Load data from the second sheet into another dataframe and set the second row as header
df2 = pd.read_excel(excel_file, sheet_name=excel_sheets[1], header=1)
print(f"\nData from sheet '{excel_sheets[1]}':")
display(df2.head())

Data from sheet 'CANINOS':

,Unnamed: 0,Unnamed: 1,Unnamed: 2,RESEÑA,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,NaN,NaT,NaN,IDENTIFICACIÓN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,TEST RAPIDO,NaN,NaN,NaN,NaN,NaN
1,NaN,NaT,Paciente,BARRIO,Epecie,Raza,Edad/meses,Sexo,peso/kg,Desparasitaciones,...,Babesia spp,Hepatozoon spp.,Mycoplasma spp,Microfilaria,Anaplasma spp.,Erliquea spp,Babesia spp,Hepatozoon spp.,Mycoplasma spp,Microfilaria
2,LUNA MOSQUERS,NaT,1,NaN,Canino,NaN,7,Hembra,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SALCHIPAPA PERALTA,NaT,2,NaN,Canino,NaN,1,Macho,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Data from sheet 'FELINOS':

,Unnamed: 0,Unnamed: 1,Unnamed: 2,IDENTIFICACIÓN,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,TEST RAPIDO,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,NaN,NaT,Paciente,BARRIO,Epecie,Raza,Edad/meses,Sexo,peso/kg,Desparasitaciones,...,Babesia spp,Hepatozoon spp.,Mycoplasma spp,Microfilaria,Anaplasma spp.,Erliquea spp,Babesia spp,Hepatozoon spp.,Mycoplasma spp,Microfilaria
1,FELIX TRELLES,2025-01-08,1,NaN,Felino,Mestizo,4,Macho,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TARQUINO BALCAZAE,2025-01-15,2,NaN,Felino,Mestizo,3,Macho,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PECHAN IÑIGUEZ,2025-01-16,3,NaN,Felino,Mestizo,9,Macho,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HARVEY CABRERA SERRANO,2025-01-16,4,NaN,Felino,Persa,6,Macho,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 51 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Unnamed: 0                                 44 non-null     object
 1   Unnamed: 1                                 44 non-null     datetime64[ns]
 2   Unnamed: 2                                 101 non-null    object
 3   IDENTIFICACIÓN                             1 non-null      object
 4   Unnamed: 4                                 45 non-null     object
 5   Unnamed: 5                                 45 non-null     object
 6   Unnamed: 6                                 41 non-null     object
 7   Unnamed: 7                                 44 non-null     object
 8   Unnamed: 8                                 1 non-null      object
 9   Unnamed: 9                                 1 non-null      object
 10  Unnamed: 10                                1 non-null      object
 11  Unnamed: 11                                5 non-null      object
 12  SIGNOS DE ENFERMEDAD, MOLESTIA O DOLENCIA  1 non-null      object
 13  Unnamed: 13                                1 non-null      object
 14  Unnamed: 14                                1 non-null      object
 15  Unnamed: 15                                1 non-null      object
 16  EXAMEN FÍSICO                              1 non-null      object
 17  Unnamed: 17                                1 non-null      object
 18  Unnamed: 18                                1 non-null      object
 19  Unnamed: 19                                1 non-null      object
 20  Unnamed: 20                                1 non-null      object
 21  Unnamed: 21                                1 non-null      object
 22  Unnamed: 22                                1 non-null      object
 23  Unnamed: 23                                1 non-null      object
 24  Unnamed: 24                                1 non-null      object
 25  Unnamed: 25                                45 non-null     object
 26  Unnamed: 26                                45 non-null     object
 27  Unnamed: 27                                45 non-null     object
 28  Unnamed: 28                                45 non-null     object
 29  Unnamed: 29                                45 non-null     object
 30  Unnamed: 30                                45 non-null     object
 31  Unnamed: 31                                43 non-null     object
 32  HEMOGRAMA COMPLETO                         45 non-null     object
 33  Unnamed: 33                                45 non-null     object
 34  Unnamed: 34                                45 non-null     object
 35  Unnamed: 35                                45 non-null     object
 36  Unnamed: 36                                45 non-null     object
 37  Unnamed: 37                                45 non-null     object
 38  Unnamed: 38                                45 non-null     object
 39  FROTIS SANGUINEO                           2 non-null      object
 40  Unnamed: 40                                2 non-null      object
 41  Unnamed: 41                                2 non-null      object
 42  Unnamed: 42                                2 non-null      object
 43  Unnamed: 43                                2 non-null      object
 44  Unnamed: 44                                2 non-null      object
 45  TEST RAPIDO                                2 non-null      object
 46  Unnamed: 46                                1 non-null      object
 47  Unnamed: 47                                1 non-null      object
 48  Unnamed: 48                                1 non-null      object
 49  Unnamed: 49                                1 non-null      object
 50  Unnamed: 50                                1 non-null      object
dtypes: datetime64[ns](1), object(50)
memory usage: 40.4+ KB